=== anvlkv/red-siren/src-tauri/resources/medium-and-material/mediums.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "items": {
    "additionalProperties": false,
    "properties": {
      "phase": {
        "type": "string"
      },
      "properties": {
        "additionalProperties": false,
        "properties": {
          "density_kg_per_m3": {
            "type": "number"
          },
          "impedance_m_rayl": {
            "type": "number"
          },
          "pressure_pa": {
            "type": "number"
          },
          "speed_of_sound_m_per_s": {
            "type": "number"
          },
          "temperature_c": {
            "type": "number"
          },
          "viscosity_pa_s": {
            "type": "number"
          }
        },
        "required": [
          "density_kg_per_m3",
          "impedance_m_rayl",
          "pressure_pa",
          "speed_of_sound_m_per_s",
          "temperature_c",
          "viscosity_pa_s"
        ],
        "type": "object"
      },
      "source_id": {
        "type": "string"
      },
      "substance": {
        "type": "string"
      }
    },
    "required": [
      "phase",
      "properties",
      "source_id",
      "substance"
    ],
    "type": "object"
  },
  "title": "mediums.json",
  "type": "array"
}

=== anvlkv/red-siren/src-tauri/resources/medium-and-material/mediums.json
[
  {
    "phase": "liquid",
    "properties": {
      "density_kg_per_m3": 1878.4,
      "impedance_m_rayl": 1983966.08,
      "pressure_pa": 101320.0,
      "speed_of_sound_m_per_s": 1056.2,
      "temperature_c": -126.8,
      "viscosity_pa_s": 0.0038228
    },
    "source_id": "C431890",
    "substance": "1,1,1,2,3,3,3-Heptafluoropropane (R227ea)"
  },
  {
    "phase": "liquid",
    "properties": {
      "density_kg_per_m3": 1596.7,
      "impedance_m_rayl": 1322339.0389999999,
      "pressure_pa": 101320.0,
      "speed_of_sound_m_per_s": 828.17,
      "temperature_c": -33.15,
      "viscosity_pa_s": 0.0010555
    },
    "source_id": "C431630",
    "substance": "1,1,1,2,3,3-Hexafluoropropane (R236ea)"
  },
  {
    "phase": "liquid",
    "properties": {
      "density_kg_per_m3": 1667.8,
      "impedance_m_rayl": 1624620.658,
      "pressure_pa": 101320.0,
      "speed_of_sound_m_per_s": 974.11,
      "temperature_c": -78.55,
      "viscosity_pa_s": 0.0015964
    },
    "source_id": "C690391",
    "substance": "1,1,1,3,3,3-Hexafluoropropane (R236fa)"
  },
  {
    "phase": "liquid",
    "properties": {
      "density_kg_per_m3": 1645.9,
      "impedance_m_rayl": 2049310.0899999999,
      "pressure_pa": 101320.0,
      "speed_of_sound_m_per_s": 1245.1,
      "temperature_c": -103.15,
      "viscosity_pa_s": 0.0058133
    },
    "source_id": "C460731",
    "substance": "1,1,1,3,3-Pentafluoropropane (R245fa)"
  },
  {
    "phase": "liquid",
    "properties": {
      "density_kg_per_m3": 1591.9,
      "impedance_m_rayl": 1773694.9800000002,
      "pressure_pa": 101320.0,
      "speed_of_sound_m_per_s": 1114.2,
      "temperature_c": -62.15,
      "viscosity_pa_s": 0.0058498
    },
    "source_id": "C679867",
    "substance": "1,1,2,2,3-Pentafluoropropane (R245ca)"
  },
  {
    "phase": "liquid",
    "properties": {
      "density_kg_per_m3": 1705.0,
      "impedance_m_rayl": 1548481.0,
      "pressure_pa": 101320.0,
      "speed_of_sound_m_per_s": 908.2,
      "temperature_c": -36.22,
      "viscosity_pa_s": 0.0018188
    },
    "source_id": "C76131",
    "substance": "1,1,2-Trichloro-1,2,2-trifluoroethane (R113)"
  },
  {
    "phase": "liquid",
    "properties": {
      "density_kg_per_m3": 1441.3,
      "impedance_m_rayl": 1859421.13,
      "pressure_pa": 101320.0,
      "speed_of_sound_m_per_s": 1290.1,
      "temperature_c": -88.47,
      "viscosity_pa_s": 0.0031346
    },
    "source_id": "C1717006",
    "substance": "1,1-Dichloro-1-fluoroethane (R141b)"
  },
  {
    "phase": "liquid",
    "properties": {
      "density_kg_per_m3": 1518.1,
      "impedance_m_rayl": 956069.0179999999,
      "pressure_pa": 101330.0,
      "speed_of_sound_m_per_s": 629.78,
      "temperature_c": 3.5916,
      "viscosity_pa_s": 0.00043999
    },
    "source_id": "C76142",
    "substance": "1,2-Dichloro-1,1,2,2-tetrafluoroethane (R114)"
  },
  {
    "phase": "liquid",
    "properties": {
      "density_kg_per_m3": 1451.1,
      "impedance_m_rayl": 2115994.02,
      "pressure_pa": 101320.0,
      "speed_of_sound_m_per_s": 1458.2,
      "temperature_c": -130.43,
      "viscosity_pa_s": 0.004087
    },
    "source_id": "C75683",
    "substance": "1-Chloro-1,1-difluoroethane (R142b)"
  },
  {
    "phase": "liquid",
    "properties": {
      "density_kg_per_m3": 627.9,
      "impedance_m_rayl": 666578.6399999999,
      "pressure_pa": 101320.0,
      "speed_of_sound_m_per_s": 1061.6,
      "temperature_c": -16.55,
      "viscosity_pa_s": 0.00043892
    },
    "source_id": "C463821",
    "substance": "2,2-Dimethylpropane"
  },
  {
    "phase": "liquid",
    "properties": {
      "density_kg_per_m3": 789.05,
      "impedance_m_rayl": 1597826.25,
      "pressure_pa": 101320.0,
      "speed_of_sound_m_per_s": 2025.0,
      "temperature_c": -160.5,
      "viscosity_pa_s": 0.032819
    },
    "source_id": "C78784",
    "substance": "2-Methylbutane"
  },
  {
    "phase": "liquid",
    "properties": {
      "density_kg_per_m3": 807.57,
      "impedance_m_rayl": 1631452.914,
      "pressure_pa": 101320.0,
      "speed_of_sound_m_per_s": 2020.2,
      "temperature_c": -153.55,
      "viscosity_pa_s": 0.0368
    },
    "source_id": "C107835",
    "substance": "2-Methylpentane"
  },
  {
    "phase": "liquid",
    "properties": {
      "density_kg_per_m3": 733.89,
      "impedance_m_rayl": 1476293.1239999998,
      "pressure_pa": 101320.0,
      "speed_of_sound_m_per_s": 2011.6,
      "temperature_c": -77.66,
      "viscosity_pa_s": 0.00057082
    },
    "source_id": "C7664417",
    "substance": "Ammonia"
  },
  {
    "phase": "liquid",
    "properties": {
      "density_kg_per_m3": 1416.9,
      "impedance_m_rayl": 1222189.6020000002,
      "pressure_pa": 101320.0,
      "speed_of_sound_m_per_s": 862.58,
      "temperature_c": -189.34,
      "viscosity_pa_s": 0.00029028
    },
    "source_id": "C7440371",
    "substance": "Argon"
  },
  {
    "phase": "liquid",
    "properties": {
      "density_kg_per_m3": 894.05,
      "impedance_m_rayl": 1246573.9149999998,
      "pressure_pa": 101320.0,
      "speed_of_sound_m_per_s": 1394.3,
      "temperature_c": 5.524,
      "viscosity_pa_s": 0.00081304
    },
    "source_id": "C71432",
    "substance": "Benzene"
  },
  {
    "phase": "liquid",
    "properties": {
      "density_kg_per_m3": 735.0,
      "impedance_m_rayl": 1342992.0,
      "pressure_pa": 101320.0,
      "speed_of_sound_m_per_s": 1827.2,
      "temperature_c": -138.25,
      "viscosity_pa_s": 0.0023625
    },
    "source_id": "C106978",
    "substance": "Butane"
  },
  {
    "phase": "vapor",
    "properties": {
      "density_kg_per_m3": 2.513,
      "impedance_m_rayl": 582.2620999999999,
      "pressure_pa": 101320.0,
      "speed_of_sound_m_per_s": 231.7,
      "temperature_c": -56.558,
      "viscosity_pa_s": 1.0938e-05
    },
    "source_id": "C124389",
    "substance": "Carbon dioxide"
  },
  {
    "phase": "liquid",
    "properties": {
      "density_kg_per_m3": 849.69,
      "impedance_m_rayl": 848653.3782,
      "pressure_pa": 101320.0,
      "speed_of_sound_m_per_s": 998.78,
      "temperature_c": -204.99,
      "viscosity_pa_s": 0.00029183
    },
    "source_id": "C630080",
    "substance": "Carbon monoxide"
  },
  {
    "phase": "liquid",
    "properties": {
      "density_kg_per_m3": 1352.8,
      "impedance_m_rayl": 1961560.0,
      "pressure_pa": 101320.0,
      "speed_of_sound_m_per_s": 1450.0,
      "temperature_c": -138.85,
      "viscosity_pa_s": 0.0013583
    },
    "source_id": "C463581",
    "substance": "Carbonyl sulfide"
  },
  {
    "phase": "liquid",
    "properties": {
      "density_kg_per_m3": 1745.0,
      "impedance_m_rayl": 1561478.35,
      "pressure_pa": 101320.0,
      "speed_of_sound_m_per_s": 894.83,
      "temperature_c": -99.4,
      "viscosity_pa_s": 0.0012646
    },
    "source_id": "C76153",
    "substance": "Chloropentafluoroethane (R115)"
  },
  {
    "phase": "liquid",
    "properties": {
      "density_kg_per_m3": 1815.7,
      "impedance_m_rayl": 1947338.25,
      "pressure_pa": 101320.0,
      "speed_of_sound_m_per_s": 1072.5,
      "temperature_c": -166.15,
      "viscosity_pa_s": 0.0023866
    },
    "source_id": "C75729",
    "substance": "Chlorotrifluoromethane (R13)"
  },
  {
    "phase": "liquid",
    "properties": {
      "density_kg_per_m3": 791.1,
      "impedance_m_rayl": 1065611.7,
      "pressure_pa": 101320.0,
      "speed_of_sound_m_per_s": 1347.0,
      "temperature_c": 6.71,
      "viscosity_pa_s": 0.0012522
    },
    "source_id": "C110827",
    "substance": "Cyclohexane"
  },
  {
    "phase": "vapor",
    "properties": {
      "density_kg_per_m3": 1.921,
      "impedance_m_rayl": 480.74946,
      "pressure_pa": 101320.0,
      "speed_of_sound_m_per_s": 250.26,
      "temperature_c": -0.15,
      "viscosity_pa_s": 8.0574e-06
    },
    "source_id": "C75194",
    "substance": "Cyclopropane"
  },
  {
    "phase": "liquid",
    "properties": {
      "density_kg_per_m3": 1775.9,
      "impedance_m_rayl": 1134924.4130000002,
      "pressure_pa": 101320.0,
      "speed_of_sound_m_per_s": 639.07,
      "temperature_c": -54.15,
      "viscosity_pa_s": 0.0011811
    },
    "source_id": "C355259",
    "substance": "Decafluorobutane"
  },
  {
    "phase": "liquid",
    "properties": {
      "density_kg_per_m3": 769.29,
      "impedance_m_rayl": 1130163.9389999998,
      "pressure_pa": 101320.0,
      "speed_of_sound_m_per_s": 1469.1,
      "temperature_c": -29.65,
      "viscosity_pa_s": 0.0024369
    },
    "source_id": "C124185",
    "substance": "Decane"
  },
  {
    "phase": "liquid",
    "properties": {
      "density_kg_per_m3": 162.51,
      "impedance_m_rayl": 158096.2284,
      "pressure_pa": 101320.0,
      "speed_of_sound_m_per_s": 972.84,
      "temperature_c": -249.49,
      "viscosity_pa_s": 2.7014e-05
    },
    "source_id": "C7782390",
    "substance": "Deuterium"
  },
  {
    "phase": "liquid",
    "properties": {
      "density_kg_per_m3": 1088.5,
      "impedance_m_rayl": 1587141.8499999999,
      "pressure_pa": 101320.0,
      "speed_of_sound_m_per_s": 1458.1,
      "temperature_c": 63.819,
      "viscosity_pa_s": 0.00052052
    },
    "source_id": "C7789200",
    "substance": "Deuterium oxide"
  },
  {
    "phase": "liquid",
    "properties": {
      "density_kg_per_m3": 1789.2,
      "impedance_m_rayl": 2209840.92,
      "pressure_pa": 101320.0,
      "speed_of_sound_m_per_s": 1235.1,
      "temperature_c": -142.05,
      "viscosity_pa_s": 0.0049273
    },
    "source_id": "C75718",
    "substance": "Dichlorodifluoromethane (R12)"
  },
  {
    "phase": "liquid",
    "properties": {
      "density_kg_per_m3": 1550.2,
      "impedance_m_rayl": 1557795.98,
      "pressure_pa": 101320.0,
      "speed_of_sound_m_per_s": 1004.9,
      "temperature_c": -58.15,
      "viscosity_pa_s": 0.0008118
    },
    "source_id": "C75434",
    "substance": "Dichlorofluoromethane (R21)"
  },
  {
    "phase": "liquid",
    "properties": {
      "density_kg_per_m3": 1237.4,
